apiVersion: v1
kind:       Service
metadata:
  name: {{ include "exivity.fullname" $ -}}-glass
  labels:
    app.kubernetes.io/component: glass
    {{- include "exivity.labels" $ | indent 4 }}
spec:
  type: {{ .Values.service.glass.serviceType }}
  selector:
    app.kubernetes.io/component: glass
    {{- include "exivity.matchLabels" $ | indent 4 }}
  ports:
    - name:       http
      port:       {{ .Values.service.glass.servicePort }}
      protocol:   TCP
      targetPort: http
