apiVersion: apps/v1
kind:       Deployment
metadata:
  name: {{ include "exivity.fullname" $ -}}-chronos
  labels:
    exivity.k8s/component: chronos
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: chronos
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: chronos
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-chronos-config
        - name: config-file
          configMap:
            name: app-config-default
        - name: log
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-chronos-log
      containers:
        - name:            chronos
          image: {{ .Values.service.chronos.image }}:{{ .Values.service.chronos.tag | default (printf "exivity-%s" (.Chart.Version)) }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu:    "25m"
              memory: "50Mi"
          securityContext:
            runAsUser:  1000
            runAsGroup: 1000
          volumeMounts:
            - name:      config
              mountPath: /exivity/home/system/config
            - name:      config-file
              mountPath: /exivity/home/system
            - name:      log
              mountPath: /exivity/home/log/chronos
      imagePullSecrets:
        - name: regcred
        - name: ghcr
