apiVersion: v1
kind:       PersistentVolumeClaim
metadata:
  name: {{ include "exivity.fullname" $ -}}-chronos-config
  labels:
    exivity.k8s/component: chronos
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
{{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
{{ end }}

---
apiVersion: v1
kind:       PersistentVolumeClaim
metadata:
  name: {{ include "exivity.fullname" $ -}}-chronos-log
  labels:
    exivity.k8s/component: chronos
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.sharedVolumeAccessMode }}
  resources:
    requests:
      storage: 1Gi
{{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
{{ end }}
