apiVersion: apps/v1
kind: Deployment
metadata:
  name: chronos
  labels:
    app: exivity
    component: chronos
spec:
  selector:
    matchLabels:
      app: exivity
      component: chronos
  replicas: 1
  template:
    metadata:
      labels:
        app: exivity
        component: chronos
    spec:
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: exivity-config
      - name: config-file
        configMap:
          name: app-config-default
      - name: log
        persistentVolumeClaim:
          claimName: exivity-log
      containers:
      - name: chronos
        image: {{ .Values.images.chronos }}
        imagePullPolicy: Always
        volumeMounts:
        - name: config
          mountPath: /exivity/home/system/config
        - name: config-file
          mountPath: /exivity/home/system
        - name: log
          mountPath: /exivity/home/log/chronos
      imagePullSecrets:
      - name: ghcr
