apiVersion: v1
kind:       PersistentVolumeClaim
metadata:
  name: {{ include "exivity.fullname" $ -}}-glass-log
  labels:
    exivity.k8s/component: griffon
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.sharedVolumeAccessMode }}
  resources:
    requests:
      storage: 1Gi
{{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
{{ end }}
