apiVersion: apps/v1
kind:       Deployment
metadata:
  name: {{ include "exivity.fullname" $ -}}-glass
  labels:
    exivity.k8s/component: glass
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: glass
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: glass
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      volumes:
        - name: log
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-glass-log
      containers:
        - name:            glass
          image: {{ .Values.service.glass.image }}:{{ .Values.service.glass.tag | default (printf "exivity-%s" (.Chart.Version)) }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu:    "25m"
              memory: "50Mi"
          securityContext:
            runAsUser:  1000
            runAsGroup: 1000
          ports:
            - containerPort: 8080
          volumeMounts:
            - name:      log
              mountPath: /exivity/home/log/glass
      imagePullSecrets:
        - name: regcred
        - name: ghcr

