apiVersion: v1
kind:       Service
metadata:
  name: {{ include "exivity.fullname" $ -}}-glass
  labels:
    exivity.k8s/component: glass
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  type: {{ .Values.ingress.serviceType }}
  selector:
    exivity.k8s/component: glass
    {{- include "exivity.default_labels" . | indent 4 }}
  ports:
    - protocol:   TCP
      port:       80
      targetPort: 8080
