apiVersion: apps/v1
kind:       Deployment
metadata:
  name: {{ include "exivity.fullname" $ -}}-horizon
  labels:
    exivity.k8s/component: horizon
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: horizon
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: horizon
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      volumes:
        - name: config
          configMap:
            name: app-config-horizon
        - name: log
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-horizon-log
      containers:
        - name:            horizon
          image: {{ .Values.service.horizon.image }}:{{ .Values.service.horizon.tag | default (printf "exivity-%s" (.Chart.Version)) }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu:    "25m"
              memory: "50Mi"
          securityContext:
            runAsUser:  1000
            runAsGroup: 1000
          volumeMounts:
            - name:      config
              mountPath: /exivity/home/system
            - name:      log
              mountPath: /exivity/home/log/horizon
            - name:      log
              mountPath: /exivity/home/log/merlin
      imagePullSecrets:
        - name: regcred
        - name: ghcr
