{{- if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exivity-ingress
  annotations:
    kubernetes.io/ingress.allow-http: 'false'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/use-regex: 'true' 
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  tls:
  - hosts:
      - {{ .Values.ingress.host }}
    secretName: {{ .Values.ingress.tlsSecret }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
        - path: /v[0-9]+?
          pathType: Prefix
          backend:
            service:
              name: proximity-api
              port:
                number: 80
        - path: '/'
          pathType: Prefix
          backend:
            service:
              name: glass
              port:
                number: 80
{{ end }}
---
{{- if .Values.ingress.generateCert }}
apiVersion: v1
kind: Secret
metadata:
  name: exivity-tls
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
data:
  {{ $ca := genCA "exivity-ca" 365 }}
  {{ $cert := genSignedCert "exivity-gui" nil (list .Values.ingress.host "localhost") 365 $ca }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
type: kubernetes.io/tls
{{ end }}
