{{if .Values.rabbitmq.install}}
apiVersion: apps/v1
kind:       StatefulSet
metadata:
  name: {{ include "exivity.fullname" $ -}}-rabbitmq
  labels:
    exivity.k8s/component: rabbitmq
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: rabbitmq
  serviceName: {{ include "exivity.fullname" $ -}}-{{- .Values.rabbitmq.host }}
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: rabbitmq
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      containers:
        - name: rabbitmq
          image: {{ .Values.service.rabbitmq.image }}:{{ .Values.service.rabbitmq.tag }}
          resources:
            requests:
              cpu:    "25m"
              memory: "50Mi"
          securityContext:
            runAsUser:  1000
            runAsGroup: 1000
          ports:
            - containerPort: 5672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.user }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password }}
            - name: RABBITMQ_DEFAULT_VHOST
              value: {{ .Values.rabbitmq.vhost }}
{{end}}
