apiVersion: v1
kind: Secret
metadata:
  name: exivity-secrets
  labels:
    app: exivity
stringData:
  app_key: {{required "A valid exivity app key needs to be provided" .Values.appKey}}
  license_key: {{required "A valid exivity license key must be provided" .Values.licenseKey}}
  jwt_secret: {{required "A valid jwt secret for proximity" .Values.JWTSecret}}
---
apiVersion: v1
kind: Secret
metadata:
  name: exivity-tls
data:
  {{$ca := genCA "exivity-ca" 365}}
  {{$cert := genSignedCert "exivity-gui" nil (list .Values.host "localhost") 365 $ca}}
  tls.crt: {{$cert.Cert | b64enc}}
  tls.key: {{$cert.Key | b64enc}}
type: kubernetes.io/tls
