apiVersion: v1
kind: Secret
metadata:
  name: exivity-app-key
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
data:
  {{- if .Release.IsUpgrade }}
  app_key: {{ index (lookup "v1" "Secret" .Release.Namespace "exivity-app-key").data "app_key" }}
  {{ else }}
  app_key: {{ randAlphaNum 32 | b64enc }}
  {{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: exivity-jwt-secret
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
data:
  {{- if .Release.IsUpgrade }}
  jwt_secret:  {{ index (lookup "v1" "Secret" .Release.Namespace "exivity-jwt-secret").data "jwt_secret" }}
  {{ else }}
  jwt_secret: {{ randAlphaNum 32 | b64enc }}
  {{ end }}
---
{{- if .Values.license }}
apiVersion: v1
kind: Secret
metadata:
  name: exivity-license-key
  labels:
    exivity.k8s/component: proximity-api
    {{- include "exivity.default_labels" . | indent 4 }}
data:
  license.key: {{ .Values.license | b64enc }}
{{ end }}
---
