apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-app-key
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
data:
  {{- if .Release.IsUpgrade }}
  app_key: {{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-app-key" (include "exivity.fullname" $))).data "app_key" }}
  {{ else }}
  app_key: {{ randAlphaNum 32 | b64enc }}
  {{ end }}

---
apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-jwt-secret
  labels:
    {{- include "exivity.default_labels" . | indent 4 }}
data:
  {{- if .Release.IsUpgrade }}
  jwt_secret: {{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-jwt-secret" (include "exivity.fullname" $))).data "jwt_secret" }}
  {{ else }}
  jwt_secret: {{ randAlphaNum 32 | b64enc }}
  {{ end }}

---
{{- if .Values.license }}
apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-license-key
  labels:
    exivity.k8s/component: proximity-api
    {{- include "exivity.default_labels" . | indent 4 }}
data:
  license.key: {{ .Values.license | b64enc }}
{{ end }}
