apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-smtp-secret
  labels:
    {{- include "exivity.labels" $ | indent 4 }}
data:
  EXIVITY_MAIL_USERNAME: "{{ .Values.smtpConfig.mail.username }}"
  EXIVITY_MAIL_PASSWORD: "{{ .Values.smtpConfig.mail.password }}"
