apiVersion: apps/v1
kind:       Deployment
metadata:
  name: {{ include "exivity.fullname" $ -}}-transcript
  labels:
    exivity.k8s/component: transcript
    {{- include "exivity.default_labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      exivity.k8s/component: transcript
  replicas: 1
  template:
    metadata:
      labels:
        exivity.k8s/component: transcript
        {{- include "exivity.default_labels" . | indent 8 }}
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-etl-config
        - name: config-file
          configMap:
            name: app-config-transcript
        - name: exported
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-exported
        - name: extracted
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-extracted
        - name: import
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-import
        - name: log
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-transcript-log
        - name: report
          persistentVolumeClaim:
            claimName: {{ include "exivity.fullname" $ -}}-report
      containers:
        - name:            transcript
          image: {{ .Values.service.transcript.image }}:{{ .Values.service.transcript.tag | default (printf "exivity-%s" (.Chart.Version)) }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu:    "25m"
              memory: "50Mi"
          securityContext:
            runAsUser:  1000
            runAsGroup: 1000
          volumeMounts:
            - name:      config
              mountPath: /exivity/home/system/config
            - name:      config-file
              mountPath: /exivity/home/system
            - name:      exported
              mountPath: /exivity/home/exported
            - name:      extracted
              mountPath: /exivity/home/system/extracted
            - name:      import
              mountPath: /exivity/home/import
            - name:      log
              mountPath: /exivity/home/log/transcript
            - name:      log
              mountPath: /exivity/home/log/merlin
            - name:      report
              mountPath: /exivity/home/system/report
          env:
            - name: EXIVITY_APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "exivity.fullname" $ -}}-app-key
                  key:  app_key
      imagePullSecrets:
        - name: regcred
        - name: ghcr
