{{ if .Values.service.tristan.enable }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ include "exivity.fullname" $ }}-edify
  labels:
    app: {{ include "exivity.fullname" $ }}
    app.kubernetes.io/component: edify
    {{- include "exivity.labels" $ | indent 4 }}
  annotations:
    checksum/{{- include "exivity.fullname" $ }}-config-edify: {{ include (print $.Template.BasePath "/edify/configmap.yaml") . | sha256sum }}
    checksum/{{- include "exivity.fullname" $ }}-rabbitmq-credentials: {{ include (print $.Template.BasePath "/rabbitmq/secret.yaml") . | sha256sum }}
    checksum/{{- include "exivity.fullname" $ }}-keda-trigger-auth-rabbitmq-conn: {{ include (print $.Template.BasePath "/keda/rabbitmq-authentication.yml") . | sha256sum }}
spec:
  jobTargetRef:
    parallelism: 1
    completions: 1
    activeDeadlineSeconds: 90000 # 25 hours
    backoffLimit: 1
    template:
      metadata:
        labels:
          app: {{ include "exivity.fullname" $ }}
          app.kubernetes.io/component: edify
          {{- include "exivity.labels" $ | indent 10 }}
      spec:
        volumes:
          - name: config-file
            configMap:
              name: {{ include "exivity.fullname" $ }}-config-edify
          - name: config
            persistentVolumeClaim:
              claimName: {{ include "exivity.fullname" $ }}-etl-config
          - name: extracted
            persistentVolumeClaim:
              claimName: {{ include "exivity.fullname" $ -}}-extracted
          - name: log
            persistentVolumeClaim:
              claimName: {{ include "exivity.fullname" $ -}}-edify-log
          - name: report
            persistentVolumeClaim:
              claimName: {{ include "exivity.fullname" $ -}}-report
        containers:
          - name: edify
            image: {{ include "exivity.image" (set $ "name" "edify") }}
            imagePullPolicy: {{ .Values.service.edify.pullPolicy | default .Values.service.pullPolicy | default "IfNotPresent" }}
            command: ["/exivity/program/bin/tristan", "-mode", "execute", "-queue", "REPORT", "-program", "/exivity/program/bin/edify"]
            env:
              - name: EXIVITY_BACKEND_LOG_LEVEL
                value: "{{ .Values.logLevel.backend }}"
              - name: LOG_LEVEL
                value: "{{ .Values.logLevel.backend }}"
              - name: METRIC_SERVER_ADDRESS
                value: "{{ include "exivity.fullname" $ -}}-tristan:50052"
              - name: SERVICE
                value: edify
              {{- if .Values.service.edify.tmpPath }}
              - name: EXIVITY_EDIFY_TMP_PATH
                value: "{{ .Values.service.edify.tmpPath }}"
              {{- end }}
            envFrom:
              - secretRef:
                  name: {{ include "exivity.fullname" $ }}-rabbitmq-credentials
            securityContext:
              runAsUser: 1000
              runAsGroup: 1000
            volumeMounts:
              - name: config
                mountPath: /exivity/home/system/config
              - name:      config-file
                mountPath: /exivity/home/system
              - name:      extracted
                mountPath: /exivity/home/system/extracted
              - name:      log
                mountPath: /exivity/home/log/edify
              - name:      log
                mountPath: /exivity/home/log/merlin
              - name:      report
                mountPath: /exivity/home/system/report
            ports:
              - containerPort: 2112
            livenessProbe:
              httpGet:
                path: /healthz
                port: 8080
              initialDelaySeconds: 5
              periodSeconds: 10
        {{- with .Values.service.pullSecrets }}
        imagePullSecrets:
          {{- range $name := .}}
          - name: {{ $name }}
          {{- end }}
        {{- end }}
        {{- if .Values.service.edify.nodeName }}
        nodeName: {{ .Values.service.edify.nodeName }}
        {{- end }}
        {{- with .Values.service.edify.nodeSelector }}
        nodeSelector:
          {{ range $key, $val := . }}
          {{ $key }}: {{ $val }}
          {{- end }}
        {{- end }}
{{ include "exivity.scalingJobSpec" (dict "values" $ "queueName" "REPORT") | indent 2 }}
{{ end }}
