{{ if .Values.service.tristan.enable }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "exivity.fullname" $ -}}-tristan
  labels:
    app.kubernetes.io/component: tristan
    {{- include "exivity.labels" $ | indent 4 }}
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: tristan
{{ end }}
