apiVersion: v1
kind:       PersistentVolumeClaim
metadata:
  name: {{ include "exivity.fullname" $ -}}-transcript-log
  labels:
    app.kubernetes.io/component: transcript
    {{- include "exivity.labels" $ | indent 4 }}
spec:
  accessModes:
    - {{ .Values.storage.sharedVolumeAccessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.pvcSizes.log.transcript }}
{{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
{{ end }}
