{{- if .Values.prometheus.metricServer.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "exivity.fullname" $ -}}-component-chronos
  labels:
    app.kubernetes.io/component: chronos
    {{- include "exivity.labels" $ | indent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: chronos
    {{- include "exivity.matchLabels" $ | indent 4 }}
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
      protocol: TCP
{{ if .Values.prometheus.metricServer.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "exivity.fullname" $ -}}-chronos
  labels:
    app.kubernetes.io/component: chronos
    {{- include "exivity.labels" $ | indent 4 }}
spec:
  endpoints:
    - interval: 5s
      path: /metrics
      port: metrics
      scheme: http
  selector:
    matchLabels:
      app.kubernetes.io/component: chronos
{{- end }}{{- end }}
