{{- if .Values.mailpit.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "exivity.fullname" . }}-mailpit
  labels:
    app.kubernetes.io/component: mailpit
    {{- include "exivity.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    - host: mailpit-{{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "exivity.fullname" . }}-mailpit
                port:
                  number: 8025
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - mailpit-{{ .Values.ingress.host }}
      secretName: {{ .Values.ingress.tlsSecretName }}
  {{- end }}
{{- end }}
