{{- if .Values.mailpit.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "exivity.fullname" . }}-mailpit
  labels:
    app.kubernetes.io/component: mailpit
    {{- include "exivity.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 8025
      targetPort: 8025
    - name: smtp
      port: 1025
      targetPort: 1025
  selector:
    app.kubernetes.io/component: mailpit
    {{- include "exivity.matchLabels" . | nindent 4 }}
{{- end }}
