apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-smtp-secret
  labels:
    {{- include "exivity.labels" $ | indent 4 }}
data:
  {{- $existingSecret := lookup "v1" "Secret" $.Release.Namespace (printf "%s-smtp-secret" (include "exivity.fullname" $)) }}
  {{- if and $.Release.IsUpgrade $existingSecret }}
  EXIVITY_MAIL_USERNAME: {{ index $existingSecret.data "EXIVITY_MAIL_USERNAME" }}
  EXIVITY_MAIL_PASSWORD: {{ index $existingSecret.data "EXIVITY_MAIL_PASSWORD" }}
  {{- else }}
  EXIVITY_MAIL_USERNAME: {{ .Values.smtp.mail.username | required ".Values.smtp.mail.username is required" | b64enc }}
  EXIVITY_MAIL_PASSWORD: {{ .Values.smtp.mail.password | required ".Values.smtp.mail.password is required" | b64enc }}
  {{- end }}
