apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-smtp-secret
  labels:
    {{- include "exivity.labels" $ | indent 4 }}
data:
{{- with .Values.smtp.mail.username }}
  EXIVITY_MAIL_USERNAME: {{ . | b64enc }}
{{- end }}
{{- with .Values.smtp.mail.password }}
  EXIVITY_MAIL_PASSWORD: {{ . | b64enc }}
{{- end }}
