{{- if and .Values.communications.smtp .Values.communications.smtp.auth .Values.communications.smtp.auth.username .Values.communications.smtp.auth.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exivity.fullname" $ }}-smtp-secret
  labels:
    {{- include "exivity.labels" $ | indent 4 }}
type: Opaque
data:
  EXIVITY_MAIL_USERNAME: {{ .Values.communications.smtp.auth.username | b64enc }}
  EXIVITY_MAIL_PASSWORD: {{ .Values.communications.smtp.auth.password | b64enc }}
{{- end }}
