apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-smtp-secret
  labels:
    {{- include "exivity.labels" $ | indent 4 }}
data:
  EXIVITY_MAIL_USERNAME: {{ .Values.smtp.mail.username | required ".Values.smtp.mail.username is required" | b64enc }}
  EXIVITY_MAIL_PASSWORD: {{ .Values.smtp.mail.password | required ".Values.smtp.mail.password is required" | b64enc }}
