{{- if .Values.communications.smtp }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exivity.fullname" $ }}-config-smtp
  labels:
    {{- include "exivity.labels" $ | indent 4 }}
data:
  {{- with .Values.communications.smtp }}
  {{- if .driver }}
  EXIVITY_MAIL_DRIVER: {{ .driver | quote }}
  {{- end }}
  {{- if .host }}
  EXIVITY_MAIL_HOST: {{ .host | quote }}
  {{- end }}
  {{- if .port }}
  EXIVITY_MAIL_PORT: {{ .port | quote }}
  {{- end }}
  {{- if .fromAddress }}
  EXIVITY_MAIL_FROM_ADDRESS: {{ .fromAddress | quote }}
  {{- end }}
  {{- if .fromName }}
  EXIVITY_MAIL_FROM_NAME: {{ .fromName | quote }}
  {{- end }}
  {{- if .encryption }}
  EXIVITY_MAIL_ENCRYPTION: {{ .encryption | quote }}
  {{- end }}
  {{- if .smtpVerifyPeer }}
  EXIVITY_MAIL_SMTP_VERIFY_PEER: {{ .smtpVerifyPeer | quote }}
  {{- end }}
  {{- end }}
{{- end }}
