apiVersion: batch/v1
kind: Job
metadata:
  name: dummy-data
spec:
  ttlSecondsAfterFinished: 0
  template:
    spec:
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: exivity-etl-config
        - name: env-config
          configMap:
            name: app-config-default
        - name: import
          persistentVolumeClaim:
            claimName: exivity-import
        - name: report
          persistentVolumeClaim:
            claimName: exivity-report
        - name: exported
          persistentVolumeClaim:
            claimName: exivity-exported
        - name: extracted
          persistentVolumeClaim:
            claimName: exivity-extracted
      containers:
        - name: dummy-data
          image: exivity/dummy-data:master
          imagePullPolicy: Always
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          volumeMounts:
            - name: config
              mountPath: /exivity/home/system/config
            - name: env-config
              mountPath: /exivity/home/system
            - name: exported
              mountPath: /exivity/home/exported
            - name: extracted
              mountPath: /exivity/home/system/extracted
            - name: import
              mountPath: /exivity/home/import
            - name: report
              mountPath: /exivity/home/system/report
      imagePullSecrets:
        - name: regcred
        - name: ghcr
      restartPolicy: Never
  backoffLimit: 4
  completions: 1
