apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-admin-credentials
  labels:
    app.kubernetes.io/component: migrate
    {{- include "exivity.labels" $ | indent 4 }}
data:
  ADMIN_USERNAME: {{ .Values.admin.username | b64enc }}
  ADMIN_PASSWORD: {{ .Values.admin.password | b64enc }}
