apiVersion: v1
kind:       ConfigMap
metadata:
  name: {{ include "exivity.fullname" $ -}}-proximity-api-env
  labels:
    app.kubernetes.io/component: proximity-api
    {{- include "exivity.labels" $ | indent 4 }}
data:
  REDIS_HOST: exivity-redis-master
  CACHE_DRIVER: file
  QUEUE_CONNECTION: sync
  NGINX_LOG_PATH: /var/log/nginx
  EXIVITY_BACKEND_LOG_LEVEL: "{{ .Values.logLevel.backend }}"
  ENABLE_PROMETHEUS: "{{ .Values.prometheus.metricServer.enabled }}"
  {{- if .Values.ingress.trustedProxy }}
  TRUSTED_PROXY: "{{ .Values.ingress.trustedProxy }}"
  {{- end }}
  {{- if .Values.service.proximityApi.phpMemoryLimit }}
  PHP_MEMORY_LIMIT: "{{ .Values.service.proximityApi.phpMemoryLimit }}"
  {{- end }}
  {{- if .Values.service.proximityApi.fingerPrinter }}
  EXIVITY_FINGERPRINTER: "{{ .Values.service.proximityApi.fingerPrinter }}"
  {{- end }}