apiVersion: v1
kind:       PersistentVolumeClaim
metadata:
  name: {{ include "exivity.fullname" $ -}}-proximity-api-log
  labels:
    app.kubernetes.io/component: proximity-api
    {{- include "exivity.labels" $ | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
{{- if .Values.storage.storageClass }}
  storageClassName: {{ .Values.storage.storageClass }}
{{ end }}
