apiVersion: v1
kind:       Service
metadata:
  name: {{ include "exivity.fullname" $ -}}-proximity-api
  labels:
    app.kubernetes.io/component: proximity-api
    {{- include "exivity.labels" $ | indent 4 }}
spec:
  type: {{ .Values.service.proximityApi.serviceType }}
  selector:
    app.kubernetes.io/component: proximity-api
    {{- include "exivity.matchLabels" $ | indent 4 }}
  ports:
    - name:       http
      port:       {{ .Values.service.proximityApi.servicePort }}
      protocol:   TCP
      targetPort: http
