apiVersion: v1
kind:       Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-app-key
  labels:
    app.kubernetes.io/component: proximity-cli
    {{- include "exivity.labels" $ | indent 4 }}
data:
  {{- if (and .Release.IsUpgrade (not .Values.secret.appKey)) }}
  app_key: {{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-app-key" (include "exivity.fullname" $))).data "app_key" }}
  {{- else }}
  app_key: {{ .Values.secret.appKey | required "An appKey is required during initial installation" | b64enc }}
  {{- end }}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-jwt-secret
  labels:
    app.kubernetes.io/component: proximity-cli
    {{- include "exivity.labels" $ | indent 4 }}
data:
  {{- if (and .Release.IsUpgrade (not .Values.secret.jwtSecret)) }}
  jwt_secret: {{ index (lookup "v1" "Secret" .Release.Namespace (printf "%s-jwt-secret" (include "exivity.fullname" $))).data "jwt_secret" }}
  {{- else }}
  jwt_secret: {{ .Values.secret.jwtSecret | required "JwtSecret is required during initial installation" | b64enc }}
  {{- end }}