apiVersion: v1
kind:       ConfigMap
metadata:
  name: {{ include "exivity.fullname" $ -}}-proximity-cli-env
  labels:
    app.kubernetes.io/component: proximity-cli
    {{- include "exivity.labels" $ | indent 4 }}
data:
  NGINX_LOG_PATH: /var/log/nginx
  EXIVITY_BACKEND_LOG_LEVEL: "{{ .Values.logLevel.backend }}"
  ENABLE_PROMETHEUS: "{{ .Values.prometheus.metricServer.enabled }}"
  