apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "exivity.fullname" $ -}}-ldap-config
  labels:
    app.kubernetes.io/component: proximity-api
    {{- include "exivity.labels" $ | indent 4 }}
data:
  {{- if .Values.ldap.tlsCacert }}
  LDAPTLS_CACERT: {{ .Values.ldap.tlsCacertPath | quote }}
  {{- end }}
