{{- if .Values.ldap.tlsCacert }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-ldap-tls-cert
  labels:
    app.kubernetes.io/component: proximity-api
    {{- include "exivity.labels" $ | indent 4 }}
  annotations:
  {{- if .Values.storage.helmResourcePolicyKeep }}
  "helm.sh/resource-policy": keep
  {{- end }}
data:
  ldap.pem: {{ .Values.ldap.tlsCacert | required "ldap.tlsCacert cannot be empty when ldap TLS is enabled" | b64enc }}
{{- end}}
