apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exivity.fullname" $ -}}-rabbitmq-credentials
  labels:
  {{- include "exivity.labels" $ | indent 4 }}
type: Opaque
data:
  AMQP_SECURE: {{ .Values.rabbitmq.secure | toString | b64enc | quote }}
  AMQP_USER: {{ .Values.rabbitmq.auth.username | b64enc | quote }}
  AMQP_PASSWORD: {{ .Values.rabbitmq.auth.password | b64enc | quote }}
  AMQP_HOST: {{ .Values.rabbitmq.host | b64enc | quote }}
  AMQP_PORT: {{ .Values.rabbitmq.port | toString | b64enc | quote }}
  AMQP_VHOST: {{ default "/" .Values.rabbitmq.vhost | b64enc | quote }}
  {{ if .Values.rabbitmq.secure }}
  host: {{ printf "amqps://%s:%s@%s:%s%s" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password .Values.rabbitmq.host (toString .Values.rabbitmq.port) (default "/" .Values.rabbitmq.vhost) | b64enc }}
  {{ else }}
  host: {{ printf "amqp://%s:%s@%s:%s%s" .Values.rabbitmq.auth.username .Values.rabbitmq.auth.password .Values.rabbitmq.host (toString .Values.rabbitmq.port) (default "/" .Values.rabbitmq.vhost) | b64enc }}
  {{ end }}
